
environment=${practiceenvironment}


base.url.alza=https://www.alza.hu/EN/
device.to.look.for=iPhone 14 128GB purple
specific.device=iPhone 14 128GB purple

chromedriver=G:\\OneDrive\\binaries\\chromedriver\\chromedriver_.exe
