name: Build and Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
          
      # Install specific version of Chrome
      - name: Setup Chrome
        run: |
          sudo wget -q -O /etc/apt/keyrings/google-chrome.gpg https://dl.google.com/linux/linux_signing_key.pub
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          
      # Setup Chrome cache
      - name: Cache Selenium Drivers
        uses: actions/cache@v3
        with:
          path: ~/.cache/selenium
          key: ${{ runner.os }}-selenium-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-selenium-
            
      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Creating Env vars
        env:
          WAITFOR_TIME: ${{ vars.WAITFOR_TIME }}
          SUITE_XML_FILES: ${{ vars.SUITE_XML_FILES }}
          IS_DOCKER_NEEDED: ${{ vars.IS_DOCKER_NEEDED }}
        run: |
          echo "SUITE_XML_FILES=$SUITE_XML_FILES" >> $GITHUB_ENV
          echo "WAITFOR_TIME=$WAITFOR_TIME" >> $GITHUB_ENV
          echo "IS_DOCKER_NEEDED=$IS_DOCKER_NEEDED" >> $GITHUB_ENV
          echo "print out suite xml $SUITE_XML_FILES"
          
      - name: Test with Maven
        env:
          CHROME_VERSION: $(google-chrome --version | awk '{print $3}')
        run: |
          echo "Chrome version: $CHROME_VERSION"
          mvn test -Dsurefire.suiteXmlFiles=${{ vars.SUITE_XML_FILES }} \
                   -Dwaitfortime=${{ vars.WAITFOR_TIME }} \
                   -Ddocker=${{ vars.IS_DOCKER_NEEDED }} \
                   -Dwebdriver.chrome.whitelistedIps="" \
                   -Dwebdriver.chrome.version=$CHROME_VERSION
        
      - name: Upload surefire report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: target/surefire-reports/emailable-report.html
          
      - name: Upload JSON files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: JSON-files
          path: src/test/java/outputstream*.json
