# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - pipeline
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - pipeline
      - main
    paths:
      - .github/workflows/selenium_tests.yml
      

    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: 17
        distribution: 'temurin'
        cache: maven
        server-id: github 

        settings-path: ${{ github.workspace }} 
        
    - name: Cache Maven local repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Google Chrome 
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

        # If using Maven, uncomment the following line
        # mvn test

    - name: Creating Env vars
      env:
        WAITFOR_TIME: ${{ vars.WAITFOR_TIME }}
        SUITE_XML_FILES: ${{ vars.SUITE_XML_FILES }}
      run: echo "print out suite xml $SUITE_XML_FILES"

    - name: Test with Maven

      run: mvn test -Dsurefire.suiteXmlFiles=$SUITE_XML_FILES -Dwaitfortime=$WAITFOR_TIME


