name: Build and Test

on:
  workflow_dispatch:
env:
  HUB_IP: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install Docker using convenience script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo docker --version

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Creating Env vars
        env:
          WAITFOR_TIME: ${{ vars.WAITFOR_TIME }}
          SUITE_XML_FILES: ${{ vars.SUITE_XML_FILES }}
        run: echo "print out suite xml $SUITE_XML_FILES"

      - name: Test with Maven
        run: mvn test -Dsurefire.suiteXmlFiles=${{ vars.SUITE_XML_FILES }} -Dwaitfortime=${{ vars.WAITFOR_TIME }} -Dgrid-hub=${{ env.HUB_IP }}

      - name: Upload surefire report
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: target/surefire-reports/emailable-report.html
